2024-02-07 15:18:34,257 - process_api - INFO - run schema: "Theme Designer Bug"
2024-02-07 15:18:34,257 - process_api - INFO - run process: "main"
2024-02-07 15:18:34,257 - process_api - INFO - run step: "start"
2024-02-07 15:18:34,257 - process_api - INFO - perform navigate: ${state.server}/#theme-designer
2024-02-07 15:18:34,272 - process_api - INFO - perform refresh
2024-02-07 15:18:35,475 - process_api - INFO - run step: "set_variables_for_profile"
2024-02-07 15:18:35,475 - process_api - INFO - perform set_uuid_variables {'variables': ['$d{id}']}
2024-02-07 15:18:35,477 - process_api - INFO - run step: "wait_for_account_button"
2024-02-07 15:18:35,477 - process_api - INFO - wait for element: {'query': '.form-container #btn-account'}
2024-02-07 15:18:38,984 - process_api - INFO - run step: "open_accounts_panel"
2024-02-07 15:18:38,984 - process_api - INFO - perform click on .form-container #btn-account
2024-02-07 15:18:39,286 - process_api - INFO - run step: "wait_for_accounts_panel"
2024-02-07 15:18:39,286 - process_api - INFO - wait for attribute: {'query': 'pr-account', 'attr': 'status', 'value': 'ready'}
2024-02-07 15:19:09,374 - process_api - ERROR - Message: 

2024-02-07 15:19:09,374 - process_api - ERROR - Traceback (most recent call last):
  File "C:\PragmaDev\ui_testing_service\process_api\__init__.py", line 82, in run
    return await self.process_runner.run_step(self, step, ctx, process, item, callback)
  File "C:\PragmaDev\ui_testing_service\process_api\process_runner.py", line 32, in run_step
    result = await function(api, step, ctx, process, item)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\__init__.py", line 56, in get
    return await get(selenium_driver, step["args"])
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\get.py", line 20, in get
    element = await get_element(ctx, query, timeout)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\get.py", line 58, in get_element
    return wait_for_element(driver, element, wait)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\get.py", line 75, in wait_for_element
    wait.until(element_usable_callback(element))
  File "C:\PragmaDev\ui_testing_service\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


2024-02-07 15:19:09,374 - process_api - ERROR - 'NoneType' object has no attribute 'get_attribute'
2024-02-07 15:19:09,374 - process_api - ERROR - Traceback (most recent call last):
  File "C:\PragmaDev\ui_testing_service\process_api\__init__.py", line 82, in run
    return await self.process_runner.run_step(self, step, ctx, process, item, callback)
  File "C:\PragmaDev\ui_testing_service\process_api\process_runner.py", line 53, in run_step
    return await self.run_step(api, next_step, ctx, process, item, callback)
  File "C:\PragmaDev\ui_testing_service\process_api\process_runner.py", line 53, in run_step
    return await self.run_step(api, next_step, ctx, process, item, callback)
  File "C:\PragmaDev\ui_testing_service\process_api\process_runner.py", line 53, in run_step
    return await self.run_step(api, next_step, ctx, process, item, callback)
  [Previous line repeated 1 more time]
  File "C:\PragmaDev\ui_testing_service\process_api\process_runner.py", line 32, in run_step
    result = await function(api, step, ctx, process, item)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\modules\selenium_wait.py", line 65, in attribute
    await wait_for_element_details(api, step, attribute_callback, ctx, process, item)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\modules\selenium_wait.py", line 21, in wait_for_element_details
    WebDriverWait(selenium_driver, timeout).until(callback(element, args))
  File "C:\PragmaDev\ui_testing_service\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\condition_callbacks\attribute_callback.py", line 6, in _predicate
    value = element.get_attribute(args["attr"])
AttributeError: 'NoneType' object has no attribute 'get_attribute'. Did you mean: '__getattribute__'?

2024-02-07 15:19:09,374 - process_api - INFO - run process: "TC2"
2024-02-07 15:19:09,374 - process_api - INFO - run step: "start"
2024-02-07 15:19:09,374 - process_api - INFO - wait for element: {'query': '.form-container #btn-account'}
2024-02-07 15:19:09,688 - process_api - INFO - Task 80f433bb-f699-4d96-9d9e-239464a0f251 completed in 00:00:35:148
