2024-02-12 09:12:48,773 - process_api - INFO - run schema: "extension"
2024-02-12 09:12:48,773 - process_api - INFO - run process: "main"
2024-02-12 09:12:48,773 - process_api - INFO - run step: "start"
2024-02-12 09:12:48,773 - process_api - INFO - perform navigate: ${state.server}/#dashboard/AssetTree
2024-02-12 09:12:49,536 - process_api - INFO - perform refresh
2024-02-12 09:12:49,837 - process_api - INFO - run step: "just_wait"
2024-02-12 09:12:49,843 - process_api - INFO - run step: "find_element"
2024-02-12 09:18:28,555 - process_api - ERROR - Message: 

2024-02-12 09:18:28,556 - process_api - ERROR - Traceback (most recent call last):
  File "C:\PragmaDev\ui_testing_service\process_api\__init__.py", line 82, in run
    return await self.process_runner.run_step(self, step, ctx, process, item, callback)
  File "C:\PragmaDev\ui_testing_service\process_api\process_runner.py", line 32, in run_step
    result = await function(api, step, ctx, process, item)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\__init__.py", line 56, in get
    return await get(selenium_driver, step["args"])
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\get.py", line 19, in get
    element = await get_element(ctx, query, timeout)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\get.py", line 57, in get_element
    return wait_for_element(driver, element, wait)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\get.py", line 74, in wait_for_element
    wait.until(element_usable_callback(element))
  File "C:\PragmaDev\ui_testing_service\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


2024-02-12 09:18:29,072 - process_api - INFO - Task 615a4858-f38a-4f57-ac6b-ee859204b69e completed in 00:05:39:790
