2024-01-25 14:29:39,222 - process_api - INFO - run schema: "visual-dashboard-test"
2024-01-25 14:29:39,222 - process_api - INFO - run process: "main"
2024-01-25 14:29:39,222 - process_api - INFO - run step: "start"
2024-01-25 14:29:39,222 - process_api - INFO - perform navigate: ${state.server}/#dashboard/WorkOrder
2024-01-25 14:29:39,229 - process_api - INFO - run step: "wait_for_dashboard_grid_to_be_ready"
2024-01-25 14:29:39,244 - process_api - INFO - wait for attribute: {'query': '#dashboard-grid', 'attr': 'status', 'value': 'ready', 'timeout': 30}
2024-01-25 14:29:42,919 - process_api - INFO - run step: "select_visual_dashboard"
2024-01-25 14:29:42,919 - process_api - INFO - perform select_option {'query': "[id='model.selectedView'] select", 'value': 'visualDashboard'}
2024-01-25 14:29:43,057 - process_api - INFO - run step: "widget_types_of_work_ready"
2024-01-25 14:29:43,057 - process_api - INFO - wait for attribute: {'query': "pr-widget[title='Types Of Work']", 'attr': 'aria-busy', 'value': 'false'}
2024-01-25 14:30:13,198 - process_api - ERROR - Message: 

2024-01-25 14:30:13,198 - process_api - ERROR - Traceback (most recent call last):
  File "C:\PragmaDev\ui_testing_service\process_api\__init__.py", line 82, in run
    return await self.process_runner.run_step(self, step, ctx, process, item, callback)
  File "C:\PragmaDev\ui_testing_service\process_api\process_runner.py", line 32, in run_step
    result = await function(api, step, ctx, process, item)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\__init__.py", line 56, in get
    return await get(selenium_driver, step["args"])
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\get.py", line 20, in get
    element = await get_element(ctx, query, timeout)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\get.py", line 51, in get_element
    return await get_element_on_path(driver, query, timeout)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\automation\get.py", line 90, in get_element_on_path
    element = wait.until(light_and_shadow_dom_callback(element, shadow_root, query))
  File "C:\PragmaDev\ui_testing_service\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


2024-01-25 14:30:13,198 - process_api - ERROR - 'NoneType' object has no attribute 'get_attribute'
2024-01-25 14:30:13,198 - process_api - ERROR - Traceback (most recent call last):
  File "C:\PragmaDev\ui_testing_service\process_api\__init__.py", line 82, in run
    return await self.process_runner.run_step(self, step, ctx, process, item, callback)
  File "C:\PragmaDev\ui_testing_service\process_api\process_runner.py", line 53, in run_step
    return await self.run_step(api, next_step, ctx, process, item, callback)
  File "C:\PragmaDev\ui_testing_service\process_api\process_runner.py", line 53, in run_step
    return await self.run_step(api, next_step, ctx, process, item, callback)
  File "C:\PragmaDev\ui_testing_service\process_api\process_runner.py", line 53, in run_step
    return await self.run_step(api, next_step, ctx, process, item, callback)
  File "C:\PragmaDev\ui_testing_service\process_api\process_runner.py", line 32, in run_step
    result = await function(api, step, ctx, process, item)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\modules\selenium_wait.py", line 53, in attribute
    await wait_for_element_details(api, step, attribute_callback, ctx, process, item)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\modules\selenium_wait.py", line 21, in wait_for_element_details
    WebDriverWait(selenium_driver, timeout).until(callback(element, args))
  File "C:\PragmaDev\ui_testing_service\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\PragmaDev\ui_testing_service\process_api\modules\selenium\condition_callbacks\attribute_callback.py", line 6, in _predicate
    value = element.get_attribute(args["attr"])
AttributeError: 'NoneType' object has no attribute 'get_attribute'. Did you mean: '__getattribute__'?

2024-01-25 14:30:13,401 - process_api - INFO - Task 2b5782df-6033-4436-b813-683b6a6f34bc completed in 00:00:33:975
